import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Search from "@/components/search";
import Record from "@/components/top-record";
import Category from "@/components/category";
import Logout from "@/components/logout";
import { useEffect, useState } from "react";

export default function Home() {
  const [cookie, setCookie] = useState(false);
  const record = () => {
    if (cookie) {
      return <Record />;
    } else {
      return <p>購入履歴はありません</p>;
    }
  };
  useEffect(() => {
    let cookie = document.cookie;

    if (cookie != null) {
      setCookie(true);
    } else {
      setCookie(false);
    }
  }, []);

  return (
    <>
      <Head>
        <title>産チョク</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>
        <div className="top_cover"></div>
        <div className="top_record">{record()}</div>
        <div className="top_search">
          <Search />
        </div>
        <div className="top_category">
          <p>生産者を探す</p>
          <Category />
        </div>
        <div className="top_recommend"></div>
      </main>
      <Logout />
      <Footer />
    </>
  );
}
